In [2]:
from pathlib import Path
import sys

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", 150)
pd.set_option("display.max_rows", 200)
pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

RANDOM_STATE = 42

In [8]:
def find_proj_root(start: Path) -> Path:
    cur = start.resolve()

    for path in [cur, *cur.parents]:
        if (path/"data").exists() and (path/"notebooks").exists():
            return path
    
    raise FileNotFoundError("Project root was not found")

PROJECT_ROOT = find_proj_root(Path.cwd())

PROJECT_ROOT = Path.cwd().parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"
REPORTS_DIR = PROJECT_ROOT/"reports"
FIGURES_DIR = REPORTS_DIR/"figures"

TRAIN_PATH = RAW_DIR / "train.csv.zip"
TEST_PATH = RAW_DIR / "test.csv.zip"
SUBMISSION_PATH = RAW_DIR / "sample_submission.csv.zip"

In [11]:
train = pd.read_csv(TRAIN_PATH)
test = pd.read_csv(TEST_PATH)
sample_submission = pd.read_csv(SUBMISSION_PATH)

print("Train shape: ", train.shape)
print("Test shape: ", test.shape)
print("Sample submission shape: ", sample_submission.shape)

Train shape:  (114321, 133)
Test shape:  (114393, 132)
Sample submission shape:  (114393, 2)

In [12]:
train.head()

,ID,target,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,v17,v18,v19,v20,v21,v22,v23,v24,v25,v26,v27,v28,v29,v30,v31,v32,v33,v34,v35,v36,v37,v38,v39,v40,v41,v42,v43,v44,v45,v46,v47,v48,v49,v50,v51,v52,v53,v54,v55,v56,v57,v58,v59,v60,v61,v62,v63,v64,v65,v66,v67,v68,v69,v70,v71,v72,v73,v74,v75,v76,v77,v78,v79,v80,v81,v82,v83,v84,v85,v86,v87,v88,v89,v90,v91,v92,v93,v94,v95,v96,v97,v98,v99,v100,v101,v102,v103,v104,v105,v106,v107,v108,v109,v110,v111,v112,v113,v114,v115,v116,v117,v118,v119,v120,v121,v122,v123,v124,v125,v126,v127,v128,v129,v130,v131
0,3,1,1.3357,8.7275,C,3.9210,7.9153,2.5993,3.1769,0.0129,10.0000,0.5033,16.4341,6.0857,2.8668,11.6364,1.3550,8.5714,3.6704,0.1067,0.1489,18.8693,7.7309,XDX,-0.0000,C,0.1394,1.7208,3.3935,0.5901,8.8809,C,A,1.0830,1.0108,7.2701,8.3755,11.3266,0.4545,0,4.0121,7.7115,7.6534,12.7076,2.0155,10.4983,9.8487,0.1136,C,12.1717,8.0866,0.8994,7.2778,G,16.7480,0.0371,1.2996,DI,3.9711,0.5298,10.8910,1.5884,15.8582,1,0.1535,6.3632,18.3039,C,9.3141,15.2318,17.1429,11.7845,F,1,1.6150,B,D,2.2309,7.2924,8.5714,E,3.0000,7.5283,8.8616,0.6498,1.2996,1.7073,0.8664,9.5518,3.3213,0.0957,0.9053,A,0.4423,5.8140,3.5177,0.4620,7.4368,5.4545,8.8774,1.1913,19.4702,8.3892,2.7574,4.3743,1.5740,0.0073,12.5792,E,2.3827,3.9309,B,0.4332,O,NaN,15.6349,2.8571,1.9512,6.5920,5.9091,-0.0000,1.0596,0.8036,8.0000,1.9898,0.0358,AU,1.8041,3.1137,2.0243,0,0.6364,2.8571
1,4,1,NaN,NaN,C,NaN,9.1913,NaN,NaN,2.3016,NaN,1.3129,NaN,6.5076,NaN,11.6364,NaN,NaN,NaN,NaN,NaN,NaN,6.7631,GUV,NaN,C,3.0561,NaN,NaN,NaN,NaN,C,A,NaN,NaN,3.6151,NaN,14.5795,NaN,0,NaN,14.3058,NaN,NaN,NaN,NaN,NaN,2.4500,E,NaN,NaN,1.3792,NaN,G,NaN,1.1295,NaN,DY,NaN,NaN,NaN,NaN,NaN,2,2.5447,NaN,NaN,A,NaN,NaN,NaN,12.0534,F,2,NaN,B,D,NaN,NaN,NaN,D,NaN,7.2777,3.4307,NaN,NaN,NaN,NaN,9.8480,NaN,2.6786,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN,8.3040,NaN,NaN,NaN,NaN,NaN,NaN,1.5053,NaN,B,1.8254,4.2479,A,NaN,U,G,10.3080,NaN,NaN,10.5954,NaN,NaN,NaN,NaN,NaN,NaN,0.5989,AF,NaN,NaN,1.9578,0,NaN,NaN
2,5,1,0.9439,5.3101,C,4.4110,5.3262,3.9796,3.9286,0.0196,12.6667,0.7659,14.7561,6.3847,2.5056,9.6035,1.9841,5.8824,3.1708,0.2445,0.1443,17.9523,5.2450,FQ,-0.0000,E,0.1140,2.2449,5.3061,0.8360,7.5000,NaN,A,1.4541,1.7347,4.0439,7.9592,12.7305,0.2597,0,7.3790,13.0772,6.1735,12.3469,2.9268,8.8976,5.3438,0.1260,C,12.7113,6.8367,0.6045,9.6376,F,15.1020,0.0856,0.7653,AS,4.0306,4.2775,9.1055,2.1514,16.0756,1,0.1236,5.5179,16.3772,A,8.3673,11.0405,5.8824,8.4607,B,3,2.4136,B,B,1.9640,5.9184,11.7647,E,3.3333,10.1944,8.2662,1.5306,1.5306,2.4299,1.0714,8.4475,3.3673,0.1114,0.8114,G,0.2715,5.1566,4.2149,0.3097,5.6633,5.9740,11.5889,0.8418,15.4913,5.8794,3.2928,5.9245,1.6684,0.0083,11.6706,C,1.3758,1.1842,B,3.3673,S,NaN,11.2056,12.9412,3.1293,3.4789,6.2338,-0.0000,2.1387,2.2388,9.3333,2.4776,0.0135,AE,1.7737,3.9222,1.1205,2,0.8831,1.1765
3,6,1,0.7974,8.3048,C,4.2259,11.6274,2.0977,1.9875,0.1719,8.9655,6.5427,16.3475,9.6467,3.9033,14.0947,1.9450,5.5172,3.6108,1.2241,0.2316,18.3764,7.5171,ACUE,-0.0000,D,0.1488,1.3083,2.3036,8.9267,8.8745,C,B,1.5876,1.6667,8.7035,8.8985,11.3028,0.4337,0,0.2873,11.5230,7.9310,12.9358,1.4709,12.7086,9.6708,0.1084,C,12.1949,8.5920,3.3292,4.7804,H,16.6217,0.1397,1.1782,BW,3.9655,1.7321,11.7779,1.2292,15.9274,1,0.1403,6.2930,17.0116,A,9.7031,18.5681,9.4253,13.5947,F,2,2.2725,B,D,2.1882,8.2136,13.4483,B,1.9473,4.7979,13.3158,1.6810,1.3793,1.5870,1.2428,10.7471,1.4080,0.0391,1.0424,B,0.7639,5.4989,3.4239,0.8325,7.3755,6.7470,6.9420,1.3346,18.2564,8.5073,2.5031,4.8722,2.5737,0.1140,12.5543,B,2.2308,1.9901,B,2.6437,J,NaN,13.7777,10.5747,1.5111,4.9496,7.1807,0.5655,1.1663,1.9565,7.0183,1.8128,0.0023,CJ,1.4152,2.9544,1.9908,1,1.6771,1.0345
4,8,1,NaN,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,1.0503,NaN,6.3201,NaN,10.9911,NaN,NaN,NaN,NaN,NaN,NaN,6.4146,HIT,NaN,E,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN,6.0832,NaN,NaN,NaN,0,NaN,10.1389,NaN,NaN,NaN,NaN,NaN,NaN,I,NaN,NaN,1.3645,NaN,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,C,NaN,NaN,NaN,NaN,F,1,NaN,B,D,NaN,NaN,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,NaN,NaN,A,NaN,T,G,14.0971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Z,NaN,NaN,NaN,0,NaN,NaN

In [13]:
test.head()

,ID,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,v17,v18,v19,v20,v21,v22,v23,v24,v25,v26,v27,v28,v29,v30,v31,v32,v33,v34,v35,v36,v37,v38,v39,v40,v41,v42,v43,v44,v45,v46,v47,v48,v49,v50,v51,v52,v53,v54,v55,v56,v57,v58,v59,v60,v61,v62,v63,v64,v65,v66,v67,v68,v69,v70,v71,v72,v73,v74,v75,v76,v77,v78,v79,v80,v81,v82,v83,v84,v85,v86,v87,v88,v89,v90,v91,v92,v93,v94,v95,v96,v97,v98,v99,v100,v101,v102,v103,v104,v105,v106,v107,v108,v109,v110,v111,v112,v113,v114,v115,v116,v117,v118,v119,v120,v121,v122,v123,v124,v125,v126,v127,v128,v129,v130,v131
0,0,1.3755,11.3611,C,4.2008,6.5770,2.0818,1.7844,0.0111,9.5238,1.3129,16.8519,6.9612,3.1075,12.2301,1.7731,2.8571,3.4938,0.0968,0.2255,17.9102,7.4378,AFPB,0.0000,E,0.0692,0.9542,4.3866,0.5730,6.9888,NaN,A,1.1152,2.0818,5.2285,8.1784,12.1832,0.8333,0,2.8428,11.7546,6.7658,10.8550,1.2963,10.6134,9.4172,0.1005,J,12.7745,7.5093,0.1188,8.5908,C,17.0213,0.0443,1.3383,AF,2.6022,0.2920,9.0386,0.8178,14.9115,1,0.0915,5.9679,15.6115,A,8.0297,15.9124,8.5714,11.2222,F,1,1.9290,B,D,2.1469,6.1710,15.7143,Q,1.9048,8.9187,8.7507,2.4535,0.8922,1.8605,0.8922,7.9050,1.7844,0.1053,0.9890,B,0.6583,4.9293,2.9924,0.7600,5.9480,5.0000,10.0135,0.8178,19.7080,4.1868,1.8739,4.1290,1.7019,0.0045,11.6881,B,1.5025,2.1217,A,3.5688,U,NaN,12.2467,11.4286,1.2766,4.7779,5.8333,-0.0000,1.4599,3.2673,7.6190,1.8152,0.0000,AF,1.2924,3.9033,1.4859,0,2.3333,1.4286
1,1,NaN,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,1.2910,NaN,6.6183,NaN,10.7608,NaN,NaN,NaN,NaN,NaN,NaN,5.8952,FOG,NaN,D,NaN,NaN,NaN,NaN,NaN,A,A,NaN,NaN,8.3874,NaN,NaN,NaN,4,NaN,6.7376,NaN,NaN,NaN,NaN,NaN,NaN,C,NaN,NaN,1.0271,NaN,A,NaN,NaN,NaN,DI,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,C,NaN,NaN,NaN,NaN,F,5,NaN,B,D,NaN,NaN,NaN,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,NaN,NaN,B,NaN,E,NaN,16.2849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I,NaN,NaN,NaN,0,NaN,NaN
2,2,-0.0000,8.2015,C,4.5444,6.5501,1.5584,2.4675,0.0072,7.1429,1.5755,15.1429,6.8942,1.8998,13.3062,1.3021,3.3333,3.1774,0.0707,0.1724,17.5375,8.2535,HXZ,-0.0000,B,0.0596,2.8571,2.2078,0.3271,8.3117,C,A,0.9740,1.5584,7.9590,8.3117,12.1951,-0.0000,0,6.7074,7.7013,6.8831,12.0779,3.4286,10.2157,7.9084,0.0822,I,12.7708,7.7922,0.8407,9.8852,A,15.0000,0.0201,0.7792,DO,5.4545,-0.0000,9.4520,2.8571,15.5611,1,0.0837,5.6337,15.7787,C,9.0909,13.2000,6.6667,7.8606,F,1,1.4881,B,D,1.9103,5.7143,16.6667,C,1.4286,8.9523,8.7449,1.9481,0.7792,1.8605,0.7792,5.8862,5.7143,0.0439,0.9187,C,0.5526,4.3510,3.1637,0.6050,6.2338,12.6316,10.2146,0.9524,19.8000,6.5356,0.7630,4.9175,1.9819,0.0028,11.7470,D,1.1888,2.0888,A,3.1169,Q,AJ,15.6227,13.3333,3.7500,4.7406,12.6316,0.0000,0.6000,2.5000,5.7143,1.9709,0.0141,AV,1.1287,5.8442,1.4759,0,1.2632,-0.0000
3,7,2.6619,3.0412,C,1.6572,9.7731,2.0783,1.4309,1.2522,7.9596,1.5755,14.4244,6.8562,5.0866,10.3970,2.8035,7.3029,1.1220,0.6085,0.4766,15.2856,5.5395,AGMU,0.0000,E,1.7800,1.4069,1.3509,5.3474,6.4748,E,A,2.3621,3.8529,6.2238,6.6347,13.7419,2.0112,0,0.0000,10.4450,6.0592,13.1894,1.8268,7.6359,12.8507,1.5042,I,16.7917,7.8018,0.9464,8.5784,A,15.3827,1.3513,3.8130,CN,4.3565,19.5354,10.4259,1.1284,10.9352,1,1.8097,2.1817,12.3661,B,8.4013,17.6771,13.1950,14.1243,F,1,3.9050,B,D,0.6446,6.3709,11.2033,C,3.5556,6.2849,3.2644,3.2374,4.2206,6.0000,1.3070,13.0371,0.4317,2.0359,1.4951,B,0.7755,3.1762,5.0713,1.0205,4.9800,8.6034,5.7436,0.6888,0.1161,3.6277,NaN,7.4862,4.3130,1.0486,5.9571,B,2.6909,6.2116,A,3.9329,F,G,13.7016,6.8050,1.9012,12.4461,10.7263,18.2448,2.3229,4.1496,4.4040,8.1636,1.1003,B,1.9887,1.5588,2.4488,0,5.3855,1.4938
4,10,1.2528,11.2834,C,4.6384,8.5205,2.3025,3.5102,0.0743,7.6129,1.0503,15.5900,6.2736,2.5002,11.3545,1.3535,3.0189,4.9740,0.5308,0.1488,18.6695,6.7415,AWW,-0.0000,E,0.1587,2.5865,3.2619,3.7866,8.8600,C,A,0.9989,1.1964,5.4769,7.7427,10.8150,0.3859,0,0.4898,11.0976,7.3815,13.1377,2.9797,12.5891,9.2373,0.1280,I,10.5796,7.8781,1.4937,5.5132,H,15.6688,0.0630,0.8804,NaN,5.2596,0.7723,11.0482,2.4624,16.9453,2,0.1235,8.1886,17.4902,B,9.4695,18.6951,9.8113,13.1470,F,2,1.4650,B,D,3.1275,7.7991,14.7170,C,1.0323,6.8373,8.7157,1.3205,0.5418,0.9524,0.8634,12.0734,2.2348,0.1500,0.9932,B,0.3900,5.6321,3.8851,0.4175,6.9413,7.6527,8.5892,1.0760,19.2277,6.6068,1.4939,4.9290,1.9069,0.0551,14.6670,B,2.4670,5.3125,A,1.8284,A,I,13.3954,10.1887,3.0318,7.6372,8.0386,0.6627,0.8522,1.6762,6.5806,1.3257,0.2585,A,1.8638,2.6665,2.3743,0,0.6817,2.2642

In [18]:
sample_submission.head()

   ID  PredictedProb
0   0         0.5000
1   1         0.5000
2   2         0.5000
3   7         0.5000
4  10         0.5000

In [19]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 114321 entries, 0 to 114320
Columns: 133 entries, ID to v131
dtypes: float64(108), int64(6), str(19)
memory usage: 118.5 MB

In [22]:
feature_cols = [col for col in train.columns if col not in ["ID", "target"]]

float_cols = train[feature_cols].select_dtypes(include="float64").columns.tolist()
int_cols = train[feature_cols].select_dtypes(include="int64").columns.tolist()
str_cols = train[feature_cols].select_dtypes(include=["string","object","str"]).columns.tolist()

print(f"All model features : {len(feature_cols)}")
print(f"Float features     : {len(float_cols)}")
print(f"Integer features   : {len(int_cols)}")
print(f"String features    : {len(str_cols)}")

print("Integer features:")
print(int_cols)

print("\nString features:")
print(str_cols)

All model features : 131
Float features     : 108
Integer features   : 4
String features    : 19
Integer features:
['v38', 'v62', 'v72', 'v129']

String features:
['v3', 'v22', 'v24', 'v30', 'v31', 'v47', 'v52', 'v56', 'v66', 'v71', 'v74', 'v75', 'v79', 'v91', 'v107', 'v110', 'v112', 'v113', 'v125']

In [26]:
for col in int_cols:
    print(f"\n")
    print(f"Feature: {col}")
    print(f"dtype: {train[col].dtype}")
    print(f"Unique values: {train[col].nunique(dropna=True)}")
    print(f"Missing values: {train[col].isna().sum()}")
    print("Values:")
    print(sorted(train[col].dropna().unique())[:50])
    print(f"\n")
    print(f"Feature: {col}")

    print(
        train[col]
        .value_counts(dropna=False)
        .sort_index()
        .head(30)
    )

Feature: v38
dtype: int64
Unique values: 12
Missing values: 0
Values:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(12)]


Feature: v38
v38
0     109724
1       2143
2       1198
3        534
4        256
5        153
6         69
7         85
8         61
9         38
10        47
12        13
Name: count, dtype: int64


Feature: v62
dtype: int64
Unique values: 8
Missing values: 0
Values:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7)]


Feature: v62
v62
0    20630
1    73830
2    16413
3     2826
4      471
5       99
6       47
7        5
Name: count, dtype: int64


Feature: v72
dtype: int64
Unique values: 13
Missing values: 0
Values:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12)]


Feature: v72
v72
0      3355
1     75767
2     24341
3      7269
4      2221
5       685
6       288
7       131
8        89
9        71
10       56
11       16
12       32
Name: count, dtype: int64


Feature: v129
dtype: int64
Unique values: 10
Missing values: 0
Values:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(11)]


Feature: v129
v129
0     90247
1     15313
2      6889
3      1373
4       357
5        83
6        45
7         3
8         3
11        8
Name: count, dtype: int64

In [29]:
global_target_rate = train["target"].mean()

print(f"Global target rate: {global_target_rate:.4f}")
print(f"Global target rate: {global_target_rate:.2%}")

int_target_profiles = {}

for col in int_cols:
    profile = (train.groupby(col)["target"].agg(count="size", target_rate="mean").reset_index())
    profile["sample_pct"] = profile["count"] / len(train) * 100
    profile["target_rate_diff"] = profile["target_rate"] - global_target_rate

    int_target_profiles[col] = profile
    print(f"\n")
    print(f"Feature: {col}")
    print(profile.to_string(index=False))

Global target rate: 0.7612
Global target rate: 76.12%


Feature: v38
 v38  count  target_rate  sample_pct  target_rate_diff
   0 109724       0.7544     95.9789           -0.0068
   1   2143       0.9118      1.8745            0.1506
   2   1198       0.9249      1.0479            0.1637
   3    534       0.9457      0.4671            0.1845
   4    256       0.9453      0.2239            0.1841
   5    153       0.9150      0.1338            0.1538
   6     69       0.9710      0.0604            0.2098
   7     85       0.9412      0.0744            0.1800
   8     61       1.0000      0.0534            0.2388
   9     38       0.9737      0.0332            0.2125
  10     47       0.8085      0.0411            0.0473
  12     13       1.0000      0.0114            0.2388


Feature: v62
 v62  count  target_rate  sample_pct  target_rate_diff
   0  20630       0.8971     18.0457            0.1359
   1  73830       0.7289     64.5813           -0.0323
   2  16413       0.7353     14.3569           -0.0259
   3   2826       0.7580      2.4720           -0.0032
   4    471       0.7877      0.4120            0.0265
   5     99       0.7273      0.0866           -0.0339
   6     47       0.9149      0.0411            0.1537
   7      5       1.0000      0.0044            0.2388


Feature: v72
 v72  count  target_rate  sample_pct  target_rate_diff
   0   3355       0.8021      2.9347            0.0409
   1  75767       0.7386     66.2757           -0.0226
   2  24341       0.7841     21.2918            0.0229
   3   7269       0.8403      6.3584            0.0791
   4   2221       0.8708      1.9428            0.1096
   5    685       0.8832      0.5992            0.1220
   6    288       0.9201      0.2519            0.1589
   7    131       0.9389      0.1146            0.1777
   8     89       0.9775      0.0779            0.2163
   9     71       0.9718      0.0621            0.2106
  10     56       1.0000      0.0490            0.2388
  11     16       0.8125      0.0140            0.0513
  12     32       0.7500      0.0280           -0.0112


Feature: v129
 v129  count  target_rate  sample_pct  target_rate_diff
    0  90247       0.7259     78.9418           -0.0353
    1  15313       0.8896     13.3947            0.1284
    2   6889       0.8964      6.0260            0.1352
    3   1373       0.9228      1.2010            0.1616
    4    357       0.9076      0.3123            0.1464
    5     83       0.8434      0.0726            0.0822
    6     45       0.9556      0.0394            0.1944
    7      3       1.0000      0.0026            0.2388
    8      3       0.6667      0.0026           -0.0945
   11      8       0.8750      0.0070            0.1138

In [30]:
integer_notes = pd.DataFrame({
    "feature": ["v38", "v62", "v72", "v129"],
    "proposed_role": [
        "discrete_count_candidate",
        "discrete_categorical_or_ordinal_candidate",
        "ordinal_count_candidate",
        "discrete_count_candidate"
    ],
    "eda_note": [
        "Strong zero/non-zero target effect",
        "Value 0 has unusually high target rate",
        "Clear increasing target trend from values 1 to 10",
        "Strong zero/non-zero target effect"
    ]
})

integer_notes

,feature,proposed_role,eda_note
0,v38,discrete_count_candidate,Strong zero/non-zero target effect
1,v62,discrete_categorical_or_ordinal_candidate,Value 0 has unusually high target rate
2,v72,ordinal_count_candidate,Clear increasing target trend from values 1 to 10
3,v129,discrete_count_candidate,Strong zero/non-zero target effect